### PR TITLE
chore: mocked testing and release process management

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by johanneskoester** [comment]
@vsoch I have implemented tests using a mocking. This allows us to test almost the entire code without any cloud costs.
I tested it manually at home, and it works flawlessly.

In order to get this to run here in the github actions, you have to set the following secrets:
* GCP_PROJECT_ID
* GCP_SA_EMAIL
* GCP_SA_KEY

It can be those of your team e.g.. Google cloud sdk just needs it for accessing the project etc. but it won't run stuff with it.

**Comment by vsoch** [comment]
Just catching up - we still need credentials for this to work, and the lab needs to provide them here? I'm not sure I can do that, but I can ask.

**Comment by johanneskoester** [comment]
Sure, that would be fine for me as well. But then the repo has to be transferred to the snakemake org. Can you do that?

**Comment by vsoch** [comment]
Done!

**Comment by johanneskoester** [comment]
@vsoch seems like the credentials are not properly loaded by the google batch api. Can you try to figure out what is wrong here?

**Comment by vsoch** [comment]
> @vsoch seems like the credentials are not properly loaded by the google batch api. Can you try to figure out what is wrong here?

The user should be authenticated on the system, and then the project and region need to be defined in the calls. E.g.,:

```
snakemake --jobs 1 --executor googlebatch --googlebatch-region us-central1 --googlebatch-project <project>
```
Or the same but in the environment using the convention:

```
export SNAKEMAKE_GOOGLEBATCH_PROJECT=<project>
export SNAKEMAKE_GOOGLEBATCH_REGION=us-central1
snakemake --jobs 1 --executor googlebatch
```

**Comment by vsoch** [comment]
For the test I think this step needs to run to setup google cloud:

image

**Comment by johanneskoester** [comment]
> For the test I think this step needs to run to setup google cloud:
> 
> image

Oh, I missed that it was actually skipped!

**Comment by vsoch** [comment]
> Oh, I missed that it was actually skipped!

Haha, no worries! That's what my extra set of :eyes: are for!

In the US today is a weird holiday where we eat lots of food and are thankful for things, and then everyone loses their mind and goes shopping tomorrow. It's not a thing outside of the US, but I'll just say happy Thanksgiving anyway! I am grateful for Snakemake and you and the community! :turkey:

**Comment by johanneskoester** [comment]
Happy thanksgiving to you as well! I can only give that back. It is always a pleasure to work with you!

**Comment by vsoch** [comment]
@johanneskoester (I’m still awake!) I’d like to spend time this weekend working on this, but the part I’m having trouble with is getting a basic example running, not from a mocked test but a Snakefile on the command line. The main issue is that since my workload upload was removed I can’t get the one provided by Snakemake to work. If we can get a hello world example working I think I can continue to make progress.

**Comment by johanneskoester** [comment]
Yay, at least the mocked tests pass now!

**Pull request merged**
