### PR TITLE
test: Testing cos again

### PR DESCRIPTION
**Pull request by cademirch**
Let's try this again :)

Checked out `testing-cos` locally, made my changes, and created this PR. I think this can be merged into `testing-cos` which can then be merged into main? Hope I got this right!

### CODE REVIEW

**Comment by vsoch** [comment]
For linting / formatting you should be able to do:

```
poetry run black <path>
poetry run flake8 <path>
```
poetry isn't my favorite, but it's used across snakemake so I know only the very basics!

**Comment by cademirch** [comment]
Looks like the tests are failing cuz the poetry dependencies are out of date, so when this eventually gets merged to main, it should be okay?

**Comment by vsoch** [comment]
Does it work locally for you? If you can try to fix the bug here that would be ideal - it won’t magically resolve merging into the or branch.

**Comment by cademirch** [comment]
I'm not sure its a bug - just the dependencies on testing-cos are out of date. I presume when testing-cos was made `snakemake-interface-executor-plugins` hadn't made it to version 9 yet, but since the snakemake dependency points to the snakemake main branch, which I guess is dynamic, it can ask for executor-plugins>9.10, even though that version didn't exist when testing-cos was made. 
```
Because snakemake (8.10.6) @ git+https://github.com/snakemake/snakemake.git@main depends on snakemake-interface-executor-plugins (>=9.1.0,<10.0)
 and snakemake-executor-plugin-googlebatch depends on snakemake-interface-executor-plugins (^8.1.1), snakemake is forbidden.
So, because snakemake-executor-plugin-googlebatch depends on snakemake (8.10.6) @ git+https://github.com/snakemake/snakemake.git@main, version solving failed.
```
Since main is ahead of testing-cos, with the correct dependencies, I figured that when testing-cos gets merged into main, the dependency issue will be resolved. If you'd like I can rebase this against main though.

**Comment by vsoch** [comment]
Try doing the update here.

**Comment by cademirch** [comment]
Done! Google auth still fails tho

**Review by vsoch — APPROVED** [review]

**Pull request merged**
