### PR TITLE
fix: make get_snakefile return rel path to snakefile

### LINKED ISSUE #39: Issues with include
Seems like there is a problem with finding rules that are specified with the `include` directive in the main Snakefile.  Using the hello_world example from this repo.

`Snakefile`:
```python
include: "rules/hello.smk"

# By convention, the first pseudorule should be called "all"
# We're using the expand() function to create multiple targets
rule all:
    input:
        expand(
            "{greeting}/world.txt",
            greeting=["hello", "hola"],
        ),
```

`hello.smk`:
```python
rule multilingual_hello_world:
    output:
        "{greeting}/world.txt",
    shell:
        """
        mkdir -p "{wildcards.greeting}"
        sleep 5
        echo "{wildcards.greeting}, World!" > {output}
        """
```

And directory structure like so:
```
.
└── workflow
    ├── Snakefile
    └── rules
        └── hello.smk
```
Executing snakemake from the root (i.e same level as workflow), the batch jobs fail complaining they can't find "/rules/hello.smk". But, if you execute from inside workflow, the batch jobs work.

### PR DESCRIPTION
**Pull request by cademirch**
Should fix #39.

### CODE REVIEW

**Comment by vsoch** [comment]
@cademirch this isn't your fault:

```
By default, secrets are not passed to workflows triggered from forks, including Dependabot.
```
Let me make a fork for you to PR to, we will merge there and then PR with that fork. We probably need to figure out a means for this to work in the future, but right now that PR will be the point where we can evaluate the code isn't being malicious, etc.

**Comment by vsoch** [comment]
Change the PR to be against this branch:

https://github.com/snakemake/snakemake-executor-plugin-googlebatch/tree/fix-snakefile-path

**Comment by vsoch** [comment]
oh looks like I can do it!

**Comment by cademirch** [comment]
Yeah I figured it wasn't me :) thanks!

**Pull request merged**
